<h1><img src='images/logo.jpeg' width='35' height='35'></img>
Sejarah</h1>
<p>
<b>Sejarah SMAN 12 Padang</b><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pada  awal&nbsp; berdirinya SMAN 12 Padang tepatnya pada&nbsp; awal tahun  pelajaran&nbsp; 1994/1995, dimana&nbsp; statusnya adalah di bawah  gendongan&nbsp; SMA NEGERI 1 Padang dan pelaksanaan proses belajar mengajar  (PBM) dilaksanakan di gedung SD Negeri 20 Nanggalo kelurahan Kurao Pagang,  Kecamatan Nanggalo Padang.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Beranjak  dari&nbsp; kondisi&nbsp; serba kekurangan, Bapak Drs Yusmar selaku&nbsp; kepala  sekolah SMAN 1 Padang menghantarkan SMA 12 Padang memiliki gedung&nbsp; sendiri  pada tahun 1996 yang berlokasi di gurun laweh kecamatan Nanggalo Padang. Atas  dukungan semua guru yang ada dan staf tata usaha dan pihak BP3 yang diketuai  oleh M Sidiq Rajo Lelo.&nbsp; Bapak Drs.Truman sebagai pelaksana harian&nbsp;  telah&nbsp; melakukan berbagai bentuk usaha untuk mengembangkan SMAN 12 Padang  mencapai stanbard pendidikan yang layak.</p>
<p>Akhir&nbsp;  tahun&nbsp; pelajaran 1995/1996 SMAN 12 Padang ditunjuk&nbsp; sebagai pelaksana  program unggulan untuk daerah Kota Padang. Hal ini&nbsp; dimaksudkan untuk  memacu&nbsp; peningkatan prestasi dan memeratakan mutu pendidikan SMA di kota  Padang. Selain itu SMA 12 Padang juga ditetapkan&nbsp; sebagai&nbsp; pelaksana  program sekolah berbakat sesuai dengan kebijakan kanwil Depdikbud Provinsi  Sumatra Barat saat itu.</p>
<p>Pada awal  tahun&nbsp; pelajaran 1996/1997 SMA Negeri 12 Padang telah berdiri sendiri  yaitu telah dilantiknya Drs. Novezar Muchtar sebagai kepala sekolah&nbsp;  definitif tepatnya pada tanggal 6 juni 1996 maka kepemimpinan II SMAN 12 Padang  dibawah pimpinan Drs. Novezar Muchtar, mulai tahun inilah SMAN 12 Padang terus  melangkah meraih prestasi dalam meningkatkan mutu pendidikan SMA di Kota  Padang. Drs Novezar Muchtar mengakhiri masa &nbsp;jabatannya pada tahun 2001.<br />
Kemajuan-kemajuan  yang telah dicapai pada kepemimpinan Drs. Novezar Muchtar dilanjutkan oleh Drs.  Agustaman yang dimulai&nbsp; pada januari 2001 sampai dengan februari 2002. Drs  Agustaman tidak lama memimpin SMAN 12 Padang karena meninggal dunia dipanggil  yang maha kuasa.</p>
<p><br />
  Kepimpinan  SMAN 12 Padang yang ke III adalah&nbsp; Drs Suardi Dahlan, beliau juga meraih  prestasi dalam mengkondisikan masyarakat gurun laweh bersaing meraih prestasi  terutama untuk masuk ke SMAN 12 Padang tidak ada lagi penerimaan siswa kelas 1  dari jatah-jatah tokoh masyarakat gurun laweh. Apa yang telah dilakukan Drs.  Suardi Dahlan dengan segala resiko dan tantangan dari ninik mamak tokoh  masyarakat gurun laweh berhasil dilewati dengan cara mengadakan dakwah ramadhan  keliling dari mesjid ke mesjid, belajar tambahan gratis di SMAN 12 Padang bagi  siswa SMA/MTS kelas III yang berdomisili di kecamatan Nanggalo. Hal ini  mendapat respon positive oleh kepala dinas pendidikan Drs. H Nur Amin, M.Pd dan  walikota padang Drs.Fauzi Bahar,M.Si dan dijadikan sikap ini sebagai cikal PSB  online di kota padang. Seiring bergulirnya mutasi dikota padang kepala sekolah  yang ke IV ini mengakhiri masa jabatannya di SMAN 12 Padang dan dimutasikan Ke  SMAN 1 Padang pada bulan juni 2004.<br />
  Kepemimpinan&nbsp;  SMAN 12 Padang yang ke IV adalah Drs. Masril, Dimasa&nbsp; kepemimpinan  Drs.Masril,M.Pd ini SMAN 12 Padang kembali meraih&nbsp; prestasi dibidang  lingkungan hidup 3 tahun berturut-turut SMAN 12 mendapat penghargaan dari  BAPEDALDA Kota padang dan provinsi dengan meraih predikat juara 1 sekolah  bernuansa lingkungan pada tahun 2006, juara harapan sekolah adiwiyata tingkat  provinsi pada tahun 2007 dan 2008 kembali meraih predikat harapan 1 sekolah  adiwiyata. Bulan juli 2008 prestasi dibidang akademik juga meningkat terlihat  dari semakin banyaknya siswa yang diterima diperguruan tinggi negeri. Selain  itu pada tahun 2007/2008 kepala sekolah yang ke IV ini meraih predikat juara 1  kepala sekolah berprestasi se kota padang, Drs.Masril,M.Pd mengakhiri masa  jabatannya di SMAN 12 Padang pada bulan juli 2008 dan dimutasikan ke SMAN 6  Padang.</p>
<p><br />
  Kepemimpinan  SMAN 12 Padang yang ke V dijalankan oleh Drs. Prima yunaldi,M.M. Kemajuan yang  telah diraih selama ini berhasil dipertahankan seperti di bidang sekolah  adiwiyata, SMA 12 Padang kembali meraih peringkat IV provinsi. Di bidang  akademik SMA 12 Padang berhasil&nbsp; meraih juara 1 olimpiade bahasa jepag  tingkat SMA yang diadakan di UNAND dan banyak prestasi lainnya. Selain itu  jumlah siswa yang tembus ke perguruan tinggi semakin meningkat dan sudah  menembuh perguruan tinggi ternama diluar Sumatra seperti UGM,UNPAD,IPB dll.  Selain itu dibidag IMTAQ terjadi perkembangan seperti gencarnya sms tahajud yang  dilakukan muri-murid hingga guru. Pada tahun pelajaran 2009/2010 SMA 12 Padang  dipercaya melaksanakan program sekolah standar nasional. Drs.Prima Yunaldi,M.M  mengakhiri jabatannya di SMA 12 pada tanggal 14 Maret 2011 dan dimutasikan ke  SMA 2 Padang.</p>
<p><br />
  Kepemimpinan  SMAN 12 Padang yang ke VI dijalankan oleh Drs.H Herman Hamad, M.Kom. saat  dipimpin oleh beliau SMA 12 Padang berhasil meraih peringkat V adiwiyata  tingkat provinsi dan peringkat I kota Padang. Pada bidang akademik SMA 12  Padang berhasil lulus 100% pada tahun 2012, dan berhasil menelorkan 8 orang  siswa jalur PMDK. Pada tahun 2011/2012 beliau berani melakukan gebrakan  penerimaan siswa baru sebanyak 360 siswa melalui psb online dan pada tahun  2012/2013 meningkat menjadi 11 kelas menjadi 440 siswa. Pada rentang  kepemimpinan Drs. Herman H, M.Kom tepatnya tahun 2011 SMA Negeri 12 Padang  ditimpa musibah kebakaran, yang meluluhlantahkan semua ruang perkantoran yang  berjumlah enam ruang dan menghanguskan seluruh kekayaan dan inventaris sekolah.  Namun Bapak Herman tidak mau tinggal diam menerima kondisi sekolah yang serba  kekurangan. Secara berangsur-angsur inventaris dan sarana pendukung  pembelajaran kembali dilengkapi, sehingga pelaksanaan pembelajaran tetap  berjalan sebagaimana mestinya. Namun pada tahun 2012 SMA Negeri 12 Padang  kembali ditimpa bencana yaitu bencana banjir bandang yang meluluhlantahkan  semua inventaris sekolah dan data siswa. Peristiwa ini cukup menghantam mental  semua stake holder yang ada di sekolah. Lingkungan sekolah yang hijau menjadi  berantakan dan dipenuhi lumpur. Musibah ini memancing kepedulian berbagai  pihak, salah satunya Direktorat Jenderal PKLK Jakarta. Dirjend PKLK ini  memberikan bantuan berupa perbaikan lingkungan, halaman dan taman sekolah serta  melengkapi kembali buku-buku perpustakaan yang habis dan hancur dilumuri lumpur  banjir bandang. </p>
<p>Gedung yang hangus terbakar juga tidak luput dari perhatian  pemerintah pusat tersebut, maka SMA Negeri 12 Padang kembali mendapat bantuan  untuk pembangunan kembali gedung yang terbakar dan pembangunan satu buah  laboratorium kimia. Pada bulan Februari 2013 &nbsp;beliau ditarik ke dinas dan  sekarang menjadi pengawas di dinas pendidikan kota  Padang.&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
  Kepemimpinan  SMA 12 Padang selanjutnya dijalankan oleh Drs. Zuwirman,M.Pd, pada masa  kepemimpinan beliau lulusan SMA Negeri 12 Padang &nbsp;diterima 46 orang  melalui jalur SNMPTN (tanpa tes) pada perguruan tinggi favorit. Pada masa  kepemimpinan Bapak Zuwirman ini SMA 12 Padang selalu berbenah dalam rangka  penciptaan lingkungan yang indah dan asri, sehingga semua siswa dan stake  holder yang ada di sekolah betah dan nyaman berada di sekolah.</p>
Kepemimpinan SMA Negeri 12 Padang tahun pelajaran  2014/2015 di pegang oleh Drs. Syamsul Bahri, M.Pd.I. Sebelumnya beliau betugas  sebagai Pengawas&nbsp; Sekolah di lingkungan Dinas Pendidikan Kota Padang. Pada  masa kepemimpinan Drs. Syamsul Bahri, M.Pd.I diaktifkan kembali kegiatan kultum  setiap Jumat pagi, dengan penampilan baru dan berubah nama menjadi kuliah  islami (KULMI). Prestasi lulusan tahun pelajaran 2013/2014 terus meningkat  menjadi 149 orang diterima di perguruan tinggi.
<p><br>
</p>
